# Generated by Django 5.0.6 on 2024-05-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='name',
            field=models.CharField(default='color', max_length=10),
            preserve_default=False,
        ),
    ]
