# Generated by Django 5.0.6 on 2024-05-21 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_color_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='color_code',
        ),
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.color'),
        ),
    ]
