# Generated by Django 5.0.6 on 2024-05-25 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_note_color_code_note_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
